#This is a simple number guessing game where the player will have to guess that which number is generated by the program in 5 tries.

import random                                       #import random library

genNum = random.randint(0, 100)                     #random number is generated by program between 0 to 100

guessCount = 0                                      #count variable to store the number of attempts
numGuessed = False                                  #boolean to check whether player guessed the number or not

print("------Number Guessing Game------\n")
print("""
Welcome to Number Guessing Game...
You have to guess the number that the program has generated for you in 5 attempts.
The number lies between 0 and 100 including both.\n
""")


while(True):
    userNum = int(input("Guess your number: "))     #take a guessed number from player
    if(userNum == genNum):                          #check if the guessed number is the generated number, if yes then the player wins
        numGuessed = True
        print("Hoorraayy you got it!!!")
        print("Thank you for playing.")
        break
    else:
        guessCount += 1                             #else increment the counter
        if(guessCount == 5):                        #check if player reached the limits of guessing
            break
        diff = abs(genNum-userNum)                  #absolute difference between generated number and guessed number
        if(diff>40):                                #giving hints
            print("Too far...")
        elif(diff>20):
            print("Little bit far...")
        else:
            print("Close...")
        print("Try again...")

if(numGuessed == False):                            #if the player is not able to guess the correct number print appropriate message
    print("Sorry you didn't get it.")
    print("Better luck next time.")
        
              


